// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Character.h"
#include "GameFramework/SpringArmComponent.h"
#include "Camera/CameraComponent.h"
#include "Components/SkeletalMeshComponent.h"
#include "Components/InputComponent.h"

///////////////////////////////////////////
#include "SuicidalController.generated.h"//
///////////////////////////////////////////

UCLASS()
//
// Class name: ASuicidalController
// Tasks:
//
//	* Handles input, generating events where needed
//  * Handles death events, spawn events, level reset events
//	* TBD
class GROUPPROJECT_API ASuicidalController : public ACharacter
{
	GENERATED_BODY()

	//
	// Constant data
	//
	
	// Input
	const FName XAxis = "MoveForward";
	const FName YAxis = "MoveLeft";
	const FName AJump = "Jump";
	
	// The attached graphics component generated by the Character.
	USkeletalMeshComponent* Graphics;

protected:
	UPROPERTY(BlueprintReadWrite, VisibleAnywhere, Category = "Components")
	USpringArmComponent* CameraSpring;

	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly, Category = "Components")
	UCameraComponent* PlayerCamera;

	UPROPERTY(VisibleAnywhere, Category = "Stats")
	FVector StoredMovement;

	UPROPERTY(VisibleAnywhere, Category = "Info")
	FVector LastRotation;

	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Movement Settings", meta = (Min = 0, Max = 1, ClampMin = 0, ClampMax = 1))
	float SmoothFactor = .5f;

	//
	// Top-down camera properties...
	//

	FVector CameraStart = FVector(-100.f, 0.f, 200.f);
	FRotator CameraTilt = FRotator(-45.f, 0.f, 0.f);

public:
	// Sets default values for this character's properties
	ASuicidalController();

protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

	UFUNCTION(BlueprintPure, Category = "Info")
	const FRotator GetDesiredRotation() const;

private:
	// Horizontal movement event
	virtual void OnHorizontalMovement(float value);

	// Vertical movement event
	virtual void OnVerticalMovement(float value);

	// Jump event
	virtual void OnJump();

	// Consumes the stored movement vector and returns it.
	const FVector ConsumeMovementVector();

public:	
	// Called every frame
	virtual void Tick(float DeltaTime) override;

	// Called to bind functionality to input
	virtual void SetupPlayerInputComponent(class UInputComponent* PlayerInputComponent) override;

	// Registers a new horizontal movement.
	UFUNCTION(BlueprintCallable, Category = "Robot Movement")
	void RegisterHorizontalMovement(const float& value);

	// Registers a new vertical movement.
	UFUNCTION(BlueprintCallable, Category = "Robot Movement")
	void RegisterVerticalMovement(const float& value);
};
